### ISSUE TITLE
meta: Report, Evaluation of Methods for Effective Control Flow Recovery

### ISSUE THREAD

**Issue by mewmew** [decomp/doc#12]
This is a *draft* of the [report](https://github.com/decomp/doc/tree/master/report/control_flow_analysis) structure.

0. [x] Abstract
1. [x] Introduction
	1. [x] Project Aim and Objectives
	2. [x] Project Thesis
	3. [x] Project Deliverables
2. [x] Methodology
	1. [x] Evaluation Process
	2. [x] Criteria for Selection of Test Programs
3. [x] Background
	1. [x] Hammock Method
	2. [ ] Interval Method
	3. [ ] Pattern-independent method
4. [x] Requirements
	1. [x] Metric for the Effectiveness of Control Flow Recovery
	2. [x] Control Flow Recovery Methods
5. [x] Results
	1. [x] Interpretation of Results
	2. [x] Combined Results
	3. [x] Recovery of 2-way Conditionals
	4. [x] Recovery of N-way Conditionals
	5. [x] Recovery of Pre-test Loops
	6. [x] Recovery of Post-test Loops
6. [ ] Evaluation
	1. [x] Metric for the Effectiveness of Control Flow Recovery
	2. [x] Control Flow Recovery Methods
	3. [ ] Effectiveness of Control Flow Recovery Methods
	4. [ ] Intuition behind Identified Deficiencies in Control Flow Recovery Methods
7. [ ] Conclusion
	1. [ ] Future Research
8. [x] Appendices
	1. [x] Control Flow Analysis Terminology
	2. [x] Control Flow Recovery Examples
	3. [x] Control Flow Recovery Results
